channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - mafft
  - iqtree
  - trimal
  - pip
  - pip:
    - streamlit
    - pandas
    - plotly
    - biopython
    - openpyxl
    - scikit-learn
    - scipy
    - seaborn
    - matplotlib
    - streamlit-aggrid
