name: phylosuite
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mafft
  - iqtree
  - trimal
  - pip
  - pip:
    - streamlit
    - pandas
    - plotly
    - biopython
